id = "diff"
name = "diff"
description = "Diff syntax highlighting with proper @diff.plus/@diff.minus support"
version = "0.0.1"
schema_version = 1
authors = ["orlaya <abc@xyz.com>"]
repository = "https://github.com/orlaya/diff_zed"

[grammars.diff]
repository = "https://github.com/orlaya/diff_tree"
commit = "24e9b2fbe4e4bbbf8d3d9dd15e0f91f10c9b1b77"
