id = "diff"
name = "diff"
description = "Diff syntax highlighting with proper @diff.plus/@diff.minus support"
version = "0.0.1"
schema_version = 1
authors = ["orlaya <abc@xyz.com>"]
repository = "https://github.com/orlaya/diff_zed"

[grammars.diff]
repository = "https://github.com/orlaya/diff_tree"
commit = "cacd891bbe0230a90b71790c1a8f480e237e43ae"
